# ============================================================
#  X-NET Blocker — Install & Run Script
# ============================================================
param (
    [string]$UserEmail = ""
)

$InstallDir = "C:\XNET"
$EmailFile = "$InstallDir\user.txt"
$HostsFile = "$env:SystemRoot\System32\drivers\etc\hosts"

# Check for Admin privileges explicitly
if (-not ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Warning "ERROR: Script is not running as Administrator. UAC prompt might have been cancelled."
    exit
}

# 1. Create working directory and save user identity
if (-not (Test-Path $InstallDir)) {
    New-Item -Path $InstallDir -ItemType Directory -Force | Out-Null
}

if ($UserEmail -ne "") {
    $UserEmail | Out-File $EmailFile -Force -Encoding ASCII
} elseif (Test-Path $EmailFile) {
    $UserEmail = Get-Content $EmailFile | Select-Object -First 1
} else {
    Write-Warning "No email found. Exiting script."
    exit
}

$SafeEmail = $UserEmail -replace '@', '_at_'
$JsonUrl = "https://raw.githubusercontent.com/meny0583285502/X-NET/main/profiles/$SafeEmail.json"

Write-Host "Fetching configuration for: $UserEmail"

# 2. Read profile data from GitHub
try {
    $ProfileData = Invoke-RestMethod -Uri $JsonUrl -UseBasicParsing -ErrorAction Stop
} catch {
    Write-Warning "Failed to communicate with server. Continuing with existing configuration."
    exit
}

# Remove ReadOnly attribute from Hosts file forcefully to prevent Access Denied
if (Test-Path $HostsFile) {
    Set-ItemProperty -Path $HostsFile -Name IsReadOnly -Value $false -ErrorAction SilentlyContinue
}

# 3. Self-Destruct Mechanism (Uninstall)
if ($ProfileData.requests.uninstall_approved -eq $true) {
    Write-Host "[+] Uninstall approved! Cleaning up system..." -ForegroundColor Green
    
    $HostsContent = Get-Content $HostsFile -Raw
    $HostsContent = $HostsContent -replace "(?s)# \[X-NET-START\].*?# \[X-NET-END\]\r?\n?", ""
    $HostsContent | Set-Content $HostsFile -Encoding UTF8 -Force

    ipconfig /flushdns | Out-Null
    schtasks /delete /tn "XNET_Blocker" /f 2>$null
    
    Write-Host "Software removed. Deleting local files..."
    Start-Sleep -Seconds 2
    Remove-Item -Path $InstallDir -Recurse -Force -ErrorAction SilentlyContinue
    exit
}

# 4. Prepare blocklist
Write-Host "Updating blocklists..."
$BlockLines = @("# [X-NET-START] - AutoGenerated DO NOT EDIT")
foreach ($Domain in $ProfileData.blocked_domains) {
    $BlockLines += "127.0.0.1 $Domain"
    $BlockLines += "127.0.0.1 www.$Domain"
}
$BlockLines += "# [X-NET-END]"
$BlockText = $BlockLines -join [Environment]::NewLine

# 5. Apply blocks to Hosts file
$HostsContent = Get-Content $HostsFile -Raw
if ($HostsContent -match "(?s)# \[X-NET-START\].*?# \[X-NET-END\]") {
    $HostsContent = $HostsContent -replace "(?s)# \[X-NET-START\].*?# \[X-NET-END\]", $BlockText
} else {
    $HostsContent = $HostsContent + [Environment]::NewLine + $BlockText
}

# Write forcefully
$HostsContent | Set-Content $HostsFile -Encoding UTF8 -Force

ipconfig /flushdns | Out-Null

# 6. Register Scheduled Task
$TaskCheck = schtasks /query /tn "XNET_Blocker" 2>$null
if ($LASTEXITCODE -ne 0) {
    Write-Host "Registering automatic startup task..."
    $Action = "powershell.exe -WindowStyle Hidden -ExecutionPolicy Bypass -Command `"Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/meny0583285502/X-NET/main/install.ps1' -OutFile 'C:\XNET\run.ps1'; & 'C:\XNET\run.ps1'`""
    schtasks /create /tn "XNET_Blocker" /tr $Action /sc onlogon /rl highest /f > $null
}

Write-Host "[+] X-NET System is Updated and Active!" -ForegroundColor Cyan
