# ============================================================
#  X-NET Blocker — Install & Run Script (FIXED LOCKS)
# ============================================================
param (
    [string]$UserEmail = ""
)

$InstallDir = "C:\XNET"
$EmailFile = "$InstallDir\user.txt"
$HostsFile = "$env:SystemRoot\System32\drivers\etc\hosts"

if (-not ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Warning "ERROR: Script is not running as Administrator."
    exit
}

if (-not (Test-Path $InstallDir)) { New-Item -Path $InstallDir -ItemType Directory -Force | Out-Null }

if ($UserEmail -ne "") {
    $UserEmail | Out-File $EmailFile -Force -Encoding ASCII
} elseif (Test-Path $EmailFile) {
    $UserEmail = Get-Content $EmailFile | Select-Object -First 1
} else {
    Write-Warning "No email found. Exiting."
    exit
}

$SafeEmail = $UserEmail -replace '@', '_at_'
$JsonUrl = "https://raw.githubusercontent.com/meny0583285502/X-NET/main/profiles/$SafeEmail.json"

Write-Host "Fetching configuration for: $UserEmail"

try {
    $ProfileData = Invoke-RestMethod -Uri $JsonUrl -UseBasicParsing -ErrorAction Stop
} catch {
    Write-Warning "Network error. Exiting."
    exit
}

# הסרת הגנת קריאה בלבד באמצעות פקודת מערכת עמוקה
if (Test-Path $HostsFile) { attrib -r $HostsFile }

# ================= מנגנון השמדה (הסרה) =================
if ($ProfileData.requests.uninstall_approved -eq $true) {
    Write-Host "Uninstall approved! Cleaning up..." -ForegroundColor Green
    $HostsContent = Get-Content $HostsFile -Raw
    $HostsContent = $HostsContent -replace "(?s)# \[X-NET-START\].*?# \[X-NET-END\]\r?\n?", ""
    
    # לולאת חילוץ לנעילת קבצים בהסרה
    $Retry = 0; $Success = $false
    while (-not $Success -and $Retry -lt 5) {
        try { $HostsContent | Out-File -FilePath $HostsFile -Encoding UTF8 -Force -ErrorAction Stop; $Success = $true }
        catch { $Retry++; Write-Host "Hosts file locked. Retrying... ($Retry/5)" -ForegroundColor Yellow; Start-Sleep -Seconds 2 }
    }

    Remove-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Google\Chrome" -Name "DnsOverHttpsMode" -ErrorAction SilentlyContinue
    Remove-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Edge" -Name "BuiltInDnsClientEnabled" -ErrorAction SilentlyContinue

    ipconfig /flushdns | Out-Null
    schtasks /delete /tn "XNET_Blocker" /f 2>$null
    Start-Sleep -Seconds 2
    Remove-Item -Path $InstallDir -Recurse -Force -ErrorAction SilentlyContinue
    exit
}

# ================= אכיפת מדיניות דפדפנים =================
Write-Host "Applying browser policies (Disabling Secure DNS)..."
$ChromeKey = "HKLM:\SOFTWARE\Policies\Google\Chrome"
if (-not (Test-Path $ChromeKey)) { New-Item -Path $ChromeKey -Force | Out-Null }
Set-ItemProperty -Path $ChromeKey -Name "DnsOverHttpsMode" -Value "off" -Force

$EdgeKey = "HKLM:\SOFTWARE\Policies\Microsoft\Edge"
if (-not (Test-Path $EdgeKey)) { New-Item -Path $EdgeKey -Force | Out-Null }
Set-ItemProperty -Path $EdgeKey -Name "BuiltInDnsClientEnabled" -Value 0 -Type DWord -Force

# ================= כתיבת החסימות =================
Write-Host "Updating blocklists..."
$BlockLines = @("# [X-NET-START] - AutoGenerated DO NOT EDIT")
foreach ($Domain in $ProfileData.blocked_domains) {
    $BlockLines += "127.0.0.1 $Domain"
    $BlockLines += "127.0.0.1 www.$Domain"
    $BlockLines += "::1 $Domain"
    $BlockLines += "::1 www.$Domain"
}
$BlockLines += "# [X-NET-END]"
$BlockText = $BlockLines -join [Environment]::NewLine

$HostsContent = Get-Content $HostsFile -Raw
if ($HostsContent -match "(?s)# \[X-NET-START\].*?# \[X-NET-END\]") {
    $HostsContent = $HostsContent -replace "(?s)# \[X-NET-START\].*?# \[X-NET-END\]", $BlockText
} else {
    $HostsContent = $HostsContent + [Environment]::NewLine + $BlockText
}

# לולאת חילוץ לנעילת קבצים (עוקף את האנטי-וירוס)
$Retry = 0; $Success = $false
while (-not $Success -and $Retry -lt 5) {
    try {
        $HostsContent | Out-File -FilePath $HostsFile -Encoding UTF8 -Force -ErrorAction Stop
        $Success = $true
    } catch {
        $Retry++
        Write-Host "File is being used by another process. Retrying in 2 seconds... ($Retry/5)" -ForegroundColor Yellow
        Start-Sleep -Seconds 2
    }
}

if (-not $Success) { Write-Warning "Failed to write to Hosts file. Antivirus might be blocking it permanently." }

ipconfig /flushdns | Out-Null

$UpdaterPath = "$InstallDir\updater.ps1"
$UpdaterCode = "Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/meny0583285502/X-NET/main/install.ps1' -OutFile 'C:\XNET\run.ps1' -UseBasicParsing -ErrorAction SilentlyContinue; & 'C:\XNET\run.ps1'"
$UpdaterCode | Out-File $UpdaterPath -Encoding UTF8 -Force

$TaskCheck = schtasks /query /tn "XNET_Blocker" 2>$null
if ($LASTEXITCODE -ne 0) {
    Write-Host "Registering automatic startup task..."
    $Action = "powershell.exe -WindowStyle Hidden -ExecutionPolicy Bypass -File `"$UpdaterPath`""
    schtasks /create /tn "XNET_Blocker" /tr $Action /sc onlogon /rl highest /f > $null
}

Write-Host "[+] X-NET System is Updated and Active!" -ForegroundColor Cyan
Write-Host ">>> IMPORTANT: Please restart Chrome/Edge to apply blocks! <<<" -ForegroundColor Yellow
